trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: 'Build Docker image'
  inputs:
    containerRegistry: 'your_docker_registry_connection'
    repository: 'your_repository_name'
    command: 'build'
    Dockerfile: 'path/to/Dockerfile'
    tags: 'your_image_tag'

- task: AWSCLI@1
  displayName: 'Login to Amazon ECR'
  inputs:
    awsCredentials: 'your_aws_credentials'
    regionName: 'your_aws_region'
    command: 'ecr get-login-password'

- script: |
    docker login -u AWS -p $(aws ecr get-login-password) your_account_id.dkr.ecr.your_region.amazonaws.com
  displayName: 'Authenticate Docker with ECR'

- task: Docker@2
  displayName: 'Push Docker image to ECR'
  inputs:
    containerRegistry: 'your_docker_registry_connection'
    repository: 'your_repository_name'
    command: 'push'
    tags: 'your_image_tag'
