trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'pipelines-javascript-docker'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: app/Dockerfile

# - task: ECRPushImage@1
#   inputs:
#     awsCredentials: 'AWS_ECR'
#     regionName: $(AWS_REGION)
#     imageSource: 'imagename'
#     sourceImageName: $(AWS_ECR_IMAGE_URI)
#     sourceImageTag: $(Build.BuildId)
#     pushTag: latest
#     repositoryName: $(AWS_ECR_REPOSITORY_NAME)
