trigger:
 - main

pool:
  vmImage: ubuntu-latest

variables:
  - group: dev

steps:
- task: ContainerBuild@0
  inputs:
    repository: $(AWS_ECR_REPOSITORY_NAME)
    Dockerfile: 'app/Dockerfile'
    tags: 'latest'
  
- script: docker images
  displayName: 'List Docker Images'

- task: ECRPushImage@1
  inputs:
    awsCredentials: 'AWS_ECR'
    regionName: $(AWS_REGION)
    imageSource: 'imagename'
    sourceImageName: $(AWS_ECR_IMAGE_URI)
    sourceImageTag: $(Build.BuildId)
    pushTag: latest
    repositoryName: $(AWS_ECR_REPOSITORY_NAME)
